default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  port: 5432
  database: EZSportsAPI_development2
  username: root
  password: root
  host: localhost
  
staging:
  <<: *default
  port: 5432
  database: EZSportsAPI_staging2
  username: root
  password: root
  host: localhost

test:
  <<: *default
  port: 5432
  database: EZSportsAPI_test2
  username: root
  password: root
  host: localhost

production:
  <<: *default
  port: 5432
  database: EZSportsAPI_development
  username: postgres
  password: 123456
  host: localhost