# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dc40a2722f330a92d90f6c9487d772775d259f2fcba35f01a96b117feaea4da277a44820dbc647e17c8f420870267641d2447b259e637cae525626a7e42d086

demo:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
test:
  secret_key_base: ab26a5be5ce9b7d30ffa64e7301260e3d10a6e81c2207d707bc602b577d296e2ae3165db9b488a14f1ffa67a427b6f5b1443a1824375c4f26c02eb6f59360f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
