Rails.application.routes.draw do


  get 'super_admin/get_sales_agents'
  post 'super_admin/save_sales_agent'
  post 'super_admin/delete_sales_agent'
  get 'super_admin/get_commission_report'

  get 'coaches/league_coaches'
  post 'coaches/new'
  post 'coaches/remove_coach'
  post 'coaches/update'
  post 'coaches/attach_coach'
  get 'coaches/select_coach'
  post 'coaches/remove_coach_from_team'
  get 'coaches/get_teams'

  get 'email/set_game_reminders'
  # post 'email/send_message'

  get 'game_schedules/coach'
  get 'game_schedules/player'
  get 'game_schedules/team_schedules'
  post 'game_schedules/upload'
  get  'game_schedules/download_sample_csv'
  resources :game_schedules
  
  get 'sports/get'
  get 'sports/test'

  get 'test/is_system_up'
  get 'test/is_database_up'

  post 'leagues/new'
  get 'leagues/get_by_user'
  post 'leagues/user'
  get 'leagues/players'
  get 'leagues/available_players'
  post 'leagues/delete'
  get 'leagues/get_player_count'
  get 'leagues/all'
  get 'leagues/get_adult_leagues'
  get 'leagues/validate_coupon'

  get 'payment/get_token'
  post 'payment/new'
  get 'payment/all'
  get 'payment/history'
  post 'payment/automated_payments'
  get 'payment/active_player_count_by_league'
  get 'payment/create_customer'
  # get 'payment/create_payment'
  post 'payment/create_league_payment'
  post 'payment/charge_users'

  get 'super_admin/get_payment_report'

  post 'player/active'
  post 'player/delete'
  post 'player/paid'
  post 'player/save'
  put 'player/update'
  put 'player/update_account'
  put 'player/update_child'
  get 'player/search'
  get 'player/email_search'
  get 'player/get_messages'
  get 'player/all_players'
  get 'player/num_players'

  get 'rosters/available_players'
  get 'rosters/show_team'
  post 'rosters/add_player_to_team'
  post 'rosters/remove_player_from_team'

  post 'seasons/save_season'
  get 'seasons/get_by_league'
  post 'seasons/delete'
  post 'seasons/update_active'

  post 'teams/create_team'
  get 'teams/get_by_league'
  get 'teams/get_by_league_active_season'
  get 'teams/get_by_season'
  post 'teams/delete'
  post 'teams/update_season'
  get 'teams/team_schedules'
  get 'teams/get_team_members'
  get 'teams/get_player_teams'


  post 'user_rosters/remove_users', to: 'user_rosters#remove_users'
  delete 'user_rosters/remove_user', to: 'user_rosters#remove_user'

  post 'users/signup'
  post 'users/admin_login'
  post 'users/team_login'
  get 'users/all'
  get 'users/get_team_user'
  post 'users/confirm_email'
  post 'users/create_adult'
  post 'users/create_child'
  post 'users/update_season'
  post 'users/update_league'
  get 'users/send_email'
  post 'users/delete'
  post 'users/paid'
  post 'users/key_login'
  post 'users/admin_key_login'
  get 'users/get_by_email'
  post 'users/active'
  get 'users/search'
  get 'users/user_leagues'
  get 'users/test'
  get 'users/get_messages'
  get 'users/get_player_messages'
  get 'users/get_coach_messages'
  get 'users/get_coach'
  post 'users/send_messages'
  post 'users/reset_password'
  post 'users/reset_team_password'
  post 'users/change_password'
  get 'users/players'
  get 'users/dupe_check'
  post 'users/reset_user_password'
  put 'users/update_admin'
  get 'users/test_logging'
  post 'users/update_cc'
  post 'users/delete_cc'

  post 'venues/add'
  get 'venues/all'
  post 'venues/delete'
  post 'venues/active'
end
