source 'https://rubygems.org'
#ruby '2.2.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'
gem 'responders', '~> 2.0'

# Use postgresql as the database for Active Record
gem 'pg'
gem 'puma'
gem 'htmlentities'
# gem 'mandrill-api'
gem 'sendgrid-ruby'
gem 'braintree'
gem 'avatax'
gem 'rack-cors', require: 'rack/cors'
gem 'time_difference'
gem 'faker'
gem 'coralogix_logger'
gem 'chronic'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
# gem 'haml'
# gem 'haml-rails'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry'
  gem 'byebug'
end

group :production do
  gem 'rails_12factor'
end
